#!/bin/bash
REPO=https://github.com/taiwancasa/sample.git
upstream=origin

npm i
rm -fr _public

git clone $REPO -b gh-pages _public

REV=`git describe --always`
gulp publish

cd _public
git add -A .
git commit -m "regen for $REV"
git push origin gh-pages
cd ..
